# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sampleUItest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod ‘Google’
  # Pods for sampleUItest

  target 'sampleUItestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sampleUItestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
